INFO:Conversion:Conversion started...
ERROR:Conversion:Conversion failed: Error: Python: Traceback (most recent call last):
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\__init__.py", line 661, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3519, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3414, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\encode_bin.py", line 314, in write
    with open(fn, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '.\\MeshFiles\\'
Location: C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\modules\bpy\ops.py:113

INFO:Conversion:Conversion started...
ERROR:Conversion:Conversion failed: Error: Python: Traceback (most recent call last):
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_mesh_ply\__init__.py", line 80, in execute
    import_ply.load(self, context, path)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_mesh_ply\import_ply.py", line 435, in load
    return load_ply(filepath)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_mesh_ply\import_ply.py", line 417, in load_ply
    mesh = load_ply_mesh(filepath, ply_name)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_mesh_ply\import_ply.py", line 237, in load_ply_mesh
    obj_spec, obj, texture = read(filepath)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_mesh_ply\import_ply.py", line 136, in read
    with open(filepath, 'rb') as plyf:
FileNotFoundError: [Errno 2] No such file or directory: '\\MeshFiles\\mesh.ply'
Location: C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\modules\bpy\ops.py:113

INFO:Conversion:Conversion started...
ERROR:Conversion:Conversion failed: Error: Python: Traceback (most recent call last):
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\__init__.py", line 661, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3519, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3414, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\encode_bin.py", line 314, in write
    with open(fn, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '.\\MeshFiles\\'
Location: C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\modules\bpy\ops.py:113

INFO:Conversion:Conversion started...
ERROR:Conversion:Conversion failed: Error: Python: Traceback (most recent call last):
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\__init__.py", line 661, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3519, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3414, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\encode_bin.py", line 314, in write
    with open(fn, 'wb') as f:
PermissionError: [Errno 13] Permission denied: './MeshFiles/'
Location: C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\modules\bpy\ops.py:113

INFO:Conversion:Conversion started...
ERROR:Conversion:Conversion failed: Error: Python: Traceback (most recent call last):
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\__init__.py", line 661, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3519, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3414, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\encode_bin.py", line 314, in write
    with open(fn, 'wb') as f:
PermissionError: [Errno 13] Permission denied: './MeshFiles/'
Location: C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\modules\bpy\ops.py:113

INFO:Conversion:Conversion started...
ERROR:Conversion:Conversion failed: Error: Python: Traceback (most recent call last):
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\__init__.py", line 661, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3519, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3414, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\addons\io_scene_fbx\encode_bin.py", line 314, in write
    with open(fn, 'wb') as f:
PermissionError: [Errno 13] Permission denied: './MeshFiles/'
Location: C:\Users\rparm\AppData\Local\Programs\Python\Python310\lib\site-packages\bpy\3.6\scripts\modules\bpy\ops.py:113

